@WebApi_HostAddress = http://localhost:5293

POST {{WebApi_HostAddress}}/appointments
Content-Type: application/json

{
  "title": "Test Appointment",
  "location": "Somewhere",
  "startDate": "2025-04-05T10:00:00Z",
  "endDate": "2025-04-05T11:00:00Z",
  "location": "Conference Room 3"
}
###

PATCH {{WebApi_HostAddress}}/appointments/30695dc3-9be9-4066-856a-51f1a340a6af/reschedule
Content-Type: application/json

{
  "id":"30695dc3-9be9-4066-856a-51f1a340a6af",
  "location": "Somewhere else",
  "newStartDate": "2025-04-06T10:00:00Z",
  "newEndDate": "2025-04-06T11:00:00Z"
}
###
